/* BullPrint Lab — the buy button, on the page that lists the prices.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * /store/ is generated by blog.py as flat HTML with no runtime, which is the
 * right call for a page crawlers must read. The consequence nobody noticed is
 * that `bpCheckout` lives in bp-forms.js, bp-forms.js only loads on the home
 * page, and so the one page on this site that shows a price had no way to take
 * a payment. Its two buttons went to a configurator anchor and a mailto.
 *
 * A store that cannot sell is not a store. This is ~130 lines of vanilla JS —
 * no framework, no runtime, nothing to hydrate — that turns the live item's
 * button into a real Stripe checkout.
 *
 * WHAT IT COLLECTS, AND WHY THAT IS THE RIGHT LIST
 * -----------------------------------------------
 * /api/checkout requires an email and a shoe, because an insole is cut to an
 * outline and made to order — there is nothing to print without them. Size
 * rides along for the print queue. Everything else a shipment needs (name,
 * address, phone) is collected by Stripe on the hosted page, so it is not asked
 * for twice and never touches this origin.
 *
 * The deeper profile — width, arch, fit, feel, cell, wall — still belongs to
 * the configurator on the home page. This form says so and links to it rather
 * than quietly shipping a thinner order under the same price.
 *
 * ONLY the live item gets a button. Slides and headbands are in the lab, so
 * they keep TELL ME WHEN. Selling what we cannot print is the exact thing the
 * line rule forbids.
 *
 * Turnstile is rendered once against <body>, outside anything that re-renders,
 * and executed per submission — the same pattern and the same sitekey as
 * bp-forms.js, for the same reason: tokens are single-use.
 */
(function () {
  "use strict";

  var SITEKEY = "0x4AAAAAAEQBxUgUlUeDfZjS";
  var widgetId = null;
  var pending = null;

  function container() {
    var el = document.getElementById("bp-turnstile");
    if (!el) {
      el = document.createElement("div");
      el.id = "bp-turnstile";
      document.body.appendChild(el);
    }
    return el;
  }

  function ready() {
    if (widgetId !== null) return true;
    if (!window.turnstile) return false;
    widgetId = window.turnstile.render(container(), {
      sitekey: SITEKEY,
      execution: "execute",
      appearance: "interaction-only",
      callback: function (t) { if (pending) { pending.resolve(t); pending = null; } },
      "error-callback": function () { if (pending) { pending.reject(new Error("net")); pending = null; } },
      "timeout-callback": function () { if (pending) { pending.reject(new Error("net")); pending = null; } },
    });
    return true;
  }

  function token() {
    return new Promise(function (resolve, reject) {
      if (!ready()) { reject(new Error("net")); return; }
      pending = { resolve: resolve, reject: reject };
      try {
        window.turnstile.reset(widgetId);
        window.turnstile.execute(widgetId);
      } catch (e) { pending = null; reject(new Error("net")); }
      setTimeout(function () {
        if (pending) { pending.reject(new Error("net")); pending = null; }
      }, 25000);
    });
  }

  function boot() {
    var form = document.getElementById("bp-buy");
    if (!form) return;
    var err = form.querySelector(".bp-buy-error");
    var btn = form.querySelector("button[type=submit]");
    var label = btn.textContent;

    function fail(msg) {
      err.textContent = msg;
      btn.disabled = false;
      btn.textContent = label;
    }

    form.addEventListener("submit", function (e) {
      e.preventDefault();
      err.textContent = "";

      var email = form.elements.email.value.trim();
      var shoe = form.elements.shoe.value.trim();
      var size = form.elements.size.value;

      // Validate here for the message, and again on the edge for the truth.
      if (!/.+@.+\..+/.test(email)) { fail("ADD AN EMAIL SO WE CAN REPLY"); return; }
      if (!shoe) { fail("TELL US THE SHOE — WE CUT THE OUTLINE TO IT"); return; }

      btn.disabled = true;
      btn.textContent = "OPENING CHECKOUT…";

      token()
        .then(function (t) {
          return fetch("/api/checkout", {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({
              token: t,
              data: {
                email: email,
                shoe: shoe,
                size: size,
                // Matches the configurator's grammar so one print queue reads
                // both paths. STORE marks where the order came from, and that
                // the deeper profile was not collected.
                profileId: "BP-" + size + "S-001",
                notes: "Ordered from /store/ — standard profile, no configurator pass.",
              },
            }),
          });
        })
        .then(function (r) {
          return r.json().then(function (b) { return { ok: r.ok, b: b }; });
        })
        .then(function (x) {
          if (x.ok && x.b && x.b.ok && x.b.url) {
            window.location.assign(x.b.url);
            return;
          }
          throw new Error((x.b && x.b.error) || "CHECKOUT IS DOWN — EMAIL THE LAB");
        })
        .catch(function (e) {
          fail(e && e.message === "net"
            ? "VERIFICATION DIDN'T LOAD — RELOAD AND RETRY"
            : (e && e.message) || "CHECKOUT IS DOWN — EMAIL THE LAB");
        });
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
