/* GENERATED by build.py from design/Bull Band Promo.dc.html.
 * Do not edit — change the design and re-run the build.
 *
 * These three assignments are inline <script> in the export. The
 * helmet manager re-creates them as inline scripts in <head>, and
 * this site's CSP is `script-src 'self'` with no 'unsafe-inline',
 * so on the deployed page they would never execute and the stage
 * would mount with no scenes at all.
 */
window.OM_SCENES = '[{"name":"Cold Open","dur":3,"desc":"Gold coin slams onto black and the BULL BAND title hits"},{"name":"Product Flex","dur":4.5,"desc":"Slow pan across the band with the comfort lines"},{"name":"The Build","dur":4.5,"desc":"Five spec chips punch in over the band"},{"name":"Bull Run","dur":4,"desc":"Gold candles climb, dont just watch the bull run, wear it"},{"name":"End Card","dur":3,"desc":"Coin, wordmark and site, fade to black"}]';
// Authored as {"mode":"loop"}.
// prefers-reduced-motion gets one pass instead of an endless one.
window.OM_PLAYBACK = (window.matchMedia &&
  window.matchMedia('(prefers-reduced-motion: reduce)').matches)
  ? '{"mode":"times","count":1}'
  : '{"mode":"loop"}';
window.TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{"motionEditor":true}/*EDITMODE-END*/;
